openapi: 3.0.3
info:
  title: Unique Tech Events
  version: "1.0.0"
  description: |
    This API provides exclusive events to learn more about STACK in Singapore.
  contact:
    email: publisher@apex.gov.sg
    name: Pub Lee Sher
tags:
  - name: Events
    description: Events related to STACK
servers:
  - url: https://demo-stack-api-lint.vercel.app/api/v4
    description: Production
    x-internal: false
security:
  - x-api-key: []
paths:
  /events:
    get:
      tags:
        - "Events"
      operationId: GetEvents
      summary: List events
      description: |
        # Endpoint for retrieving the list of unique and exciting tech events

        This endpoint will return all the registered events.

        You may specify which **country** to filter for to get specific events for specific countries.
      parameters:
        - name: country
          in: query
          examples:
            singapore:
              value: "singapore"
            canada:
              value: "canada"
            thailand:
              value: "thailand"
          schema:
            type: string
            format: /^[a-z]+$/
            maxLength: 56
            description: The country to filter events from
      responses:
        "200":
          description: Successful retrieval of events
          headers:
            X-RateLimit-Limit:
              $ref: "#/components/headers/X-RateLimit-Limit"
          content:
            application/json:
              schema:
                maxItems: 500
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      format: uuid
                      description: Unique identifier of the event
                      maxLength: 255
                      example: "c4a760a8-dbcf-4e04-9a2a-8f5d5c5f8f8f"
                    name:
                      type: string
                      pattern: "^[A-Za-z0-9- ]+$"
                      maxLength: 255
                      description: Name of the event
                      example: "STACK Tech Conference"
                    description:
                      type: string
                      pattern: "^[A-Za-z0-9- ]+$"
                      maxLength: 255
                      description: Description of the event
                      example: "Conference for developers to learn more about STACK"
                    guestSpeaker:
                      type: string
                      pattern: "^[A-Za-z- ]+$"
                      maxLength: 255
                      description: Name of the guest speaker for the event
                      example: "John Doe"
                    date:
                      type: string
                      format: date-time
                      description: Date of the event
                      maxLength: 26
                      example: "2024-07-01T03:04:42.800Z"
                    location:
                      type: string
                      pattern: "^[A-Za-z ]+$"
                      maxLength: 56
                      description: Location of the event
                      example: "singapore"
        "400":
          $ref: "#/components/responses/Error400"
        "401":
          $ref: "#/components/responses/Error401"
        "403":
          $ref: "#/components/responses/Error403"
        "429":
          $ref: "#/components/responses/Error429"
        "500":
          $ref: "#/components/responses/Error500"
  /events/{eventId}:
    post:
      tags:
        - "Events"
      operationId: RegisterForEvents
      summary: Event registration
      description: |
        # Endpoint for event registration

        Register yourself and your friends (up to 2) to attend to an event of your choice.

        Registering to an event will send you updates on the event and guarantee your seats.
      parameters:
        - name: eventId
          in: path
          description: Unique identifier of the event to register
          required: true
          schema:
            format: uuid
            type: string
            maxLength: 255
            example: "c4a760a8-dbcf-4e04-9a2a-8f5d5c5f8f8f"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                pax:
                  type: integer
                  format: int32
                  description: Number of tickets to include to this registration
                  minimum: 1
                  maximum: 3
                  example: 1
                email:
                  description: Email of the participant to receive updates on the event
                  type: string
                  format: email
                  maxLength: 50
                  example: user@example.com
                name:
                  type: string
                  description: Name of the participant
                  format: "^[A-Za-z0-9- ]+$"
                  maxLength: 24
                  minLength: 3
                  example: John Doe
                tier:
                  type: string
                  enum:
                    - "gold"
                    - "silver"
                    - "bronze"
                  description: Tier of the ticket seats
                  example: gold
      responses:
        "200":
          description: Successful registration to event
          headers:
            X-RateLimit-Limit:
              $ref: "#/components/headers/X-RateLimit-Limit"
          content:
            application/json:
              schema:
                type: object
                properties:
                  event:
                    type: string
                    description: Id of event registered
                    format: uuid
                    maxLength: 255
                    example: "c4a760a8-dbcf-4e04-9a2a-8f5d5c5f8f8f"
                  tickets:
                    type: integer
                    description: Number of tickets registered
                    format: int32
                    maximum: 3
                    minimum: 1
                    example: 1
                  for:
                    type: string
                    format: "^[A-Za-z0-9- ]+$"
                    maxLength: 25
                    description: Name of the participant
                    example: John Doe
        "400":
          $ref: "#/components/responses/Error400"
        "401":
          $ref: "#/components/responses/Error401"
        "403":
          $ref: "#/components/responses/Error403"
        "429":
          $ref: "#/components/responses/Error429"
        "500":
          $ref: "#/components/responses/Error500"
components:
  securitySchemes:
    x-exciting-event-api-key:
      type: apiKey
      name: x-exciting-event-api-key
      in: header
  headers:
    X-RateLimit-Limit:
      schema:
        type: number
      description: "Maximum number of requests allowed in a set time window (e.g., per hour)."
  responses:
    Error400:
      description: Invalid body request
      headers:
        X-RateLimit-Limit:
          $ref: "#/components/headers/X-RateLimit-Limit"
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                format: "^[A-Za-z0-9- .!]+$"
                maxLength: 255
                example: "The request body is invalid or missing required fields"
    Error401:
      description: Missing or Invalid API key
      headers:
        X-RateLimit-Limit:
          $ref: "#/components/headers/X-RateLimit-Limit"
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                format: "^[A-Za-z0-9- .!]+$"
                maxLength: 255
                example: "You have a missing or invalid API key"
    Error403:
      description: User of API key is not allowed to register to selected event
      headers:
        X-RateLimit-Limit:
          $ref: "#/components/headers/X-RateLimit-Limit"
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                format: "^[A-Za-z0-9- .!]+$"
                maxLength: 255
                example: "User of API key is not allowed to register to selected event"
    Error429:
      description: Rate limit exceeded
      headers:
        Retry-After:
          schema:
            type: integer
            format: int32
            maximum: 3600
            minimum: 100
            description: Seconds to wait before retrying the request
        X-RateLimit-Limit:
          $ref: "#/components/headers/X-RateLimit-Limit"
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                format: "^[A-Za-z0-9- .!]+$"
                maxLength: 255
                example: "You have exceeded the rate limit for this endpoint"
    Error500:
      description: Internal Server Error
      headers:
        X-RateLimit-Limit:
          $ref: "#/components/headers/X-RateLimit-Limit"
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                format: "^[A-Za-z0-9- .!]+$"
                maxLength: 255
                example: "An internal server error has occurred"
